Wumplus_World: Agent.o Wumplus_World.o
	gcc -lm  Agent.o Wumplus_World.o -o Wumplus_World
Agent.o: Agent.c Agent.h
	gcc -lm -c Agent.c
Wumplus_World.o: Agent.h Wumplus_World.c
	gcc -lm -c Wumplus_World.c